apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-models-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: netapp-file-standard
  resources:
    requests:
      storage: 30Gi
