apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: llamacpp-runtime
  annotations:
    openshift.io/display-name: "LlamaCPP"
    opendatahub.io/apiProtocol: REST
  labels:
    opendatahub.io/dashboard: "true"
spec:
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: any
  containers:
    - name: kserve-container
      image: quay.io/alexonoliveira/llamacpp_python@sha256:4c0043b34e2ac3bf5ecd583e571cbc9661c7abebca3c13c365b78441907def91
      ports:
        - containerPort: 8080
          protocol: TCP
      args:
        - --model
        - /mnt/models/qwen2.5-3b-instruct-q4_k_m.gguf
        - --host
        - "0.0.0.0"
        - --port
        - "8080"
