apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-agent
  labels:
    app: sre-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-agent
  template:
    metadata:
      labels:
        app: sre-agent
    spec:
      serviceAccountName: sre-agent
      containers:
        - name: sre-agent
          image: ghcr.io/strukalex/sre-agent:v0.1
          envFrom:
            - configMapRef:
                name: sre-agent-config
            - secretRef:
                name: sre-agent-secrets
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
