apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rhdh-manifests.yaml
  - network-policy.yaml
configMapGenerator:
  - name: rhdh-catalog-entities
    files:
      - users.yaml
    options:
      disableNameSuffixHash: true
