"""System prompts and few-shot examples for the SRE agent."""

SYSTEM_PROMPT = """You are an SRE. Respond ONLY with a JSON object. No other text.

{"root_cause":"...","severity":"critical|warning|info","suggested_fix":"...","fix_type":"restart|scale|rollback|config|none","fix_details":{"action":"...","target":"..."}}

Example - CrashLoopBackOff:
{"root_cause":"Invalid container command","severity":"critical","suggested_fix":"Rollback deployment","fix_type":"rollback","fix_details":{"action":"rollback","target":"deployment/test"}}

Example - OOMKilled:
{"root_cause":"Memory limit too low","severity":"critical","suggested_fix":"Increase memory to 256Mi","fix_type":"config","fix_details":{"action":"patch_memory","target":"deployment/test"}}

Analyze this:
"""

GITHUB_ISSUE_TEMPLATE = """## SRE Agent - Incident Report

**Deployment**: `{deployment}`
**Namespace**: `{namespace}`
**Detected at**: {timestamp}
**Severity**: {severity}

### Root Cause Analysis
{root_cause}

### Suggested Fix
{suggested_fix}

### Diagnostic Data
<details>
<summary>Pod Status</summary>

```
{pod_status}
```
</details>

<details>
<summary>Recent Events</summary>

```
{events}
```
</details>

<details>
<summary>Container Logs (last 50 lines)</summary>

```
{logs}
```
</details>

---
*Generated by SRE Agent using {model}*
"""

PR_BODY_TEMPLATE = """## SRE Agent - Automated Fix

**Related Incident**: #{issue_number}
**Fix Type**: {fix_type}

### Description
{description}

### Changes
{changes}

### Verification
After merging, verify that:
- [ ] Deployment rolls out successfully
- [ ] Health endpoint returns 200
- [ ] No OOMKilled or CrashLoopBackOff events

---
*Generated by SRE Agent using {model}*
"""
