apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-workspace-ide
spec:
  host: my-workspace-ide.apps.silver.devops.gov.bc.ca
  path: /
  port:
    targetPort: 3100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: REPLACE_SERVICE_NAME
    weight: 100
