apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fd34fb-prod
resources:
  - ../../../base/sre-agent
secretGenerator:
  - name: sre-agent-secrets
    envs:
      - .env
    options:
      disableNameSuffixHash: true
